name: build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: 'always'
          validate-wrappers: true

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Check Spotless
        run: ./gradlew spotlessCheck

  jvm-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-cleanup: 'always'
          validate-wrappers: true

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Run test
        run: ./gradlew test --rerun-tasks

      - name: Generate coverage report with Kover
        if: github.ref == 'refs/heads/main'
        run: ./gradlew koverXmlReport

      - name: Upload coverage report to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          files: app/build/reports/kover/report.xml
          token: ${{ secrets.CODECOV_TOKEN }}